Update nmap-mac-prefixes using a new script
nmap/nmap pull request #2479
Opened 2022-05-18 11:02 UTC by oh2fih

The `nmap-mac-prefixes` has not been updated in 10 months (since Aug 6, 2021; [2f8b4e2](https://github.com/nmap/nmap/commit/2f8b4e20a1995ada3f6d4fb4c1dcf070992c927a)). The source data format has also changed, making the former Perl script `make-mac-prefixes.pl` incompatible with it. The corresponding data can currently be found from IEEE MA-L Assignments (CSV) data set, as described in https://standards.ieee.org/products-programs/regauth/.

This PR adds a new Python script `make-mac-prefixes.py` for updating the prefixes. The format produced is not exactly the same, but based on the same aims. The updated `nmap-mac-prefixes` is produced with this script.

```
$ curl https://standards-oui.ieee.org/oui/oui.csv | ./make-mac-prefixes.py > nmap-mac-prefixes 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2889k  100 2889k    0     0   432k      0  0:00:06  0:00:06 --:--:--  593k
# Found 31988 registed OUIs.
# Added 5 unregisted OUIs.
```

Ref. question on the nmap-dev mailing list https://seclists.org/nmap-dev/2022/q2/6

2022-06-13 12:40 UTC, aceboogie8519 approved these changes
Merge

2022-06-13 12:51 UTC, aceboogie8519 commented
Add me so all can have the up date

2022-06-13 12:53 UTC, aceboogie8519 commented
Merge

2022-06-13 13:02 UTC, oh2fih commented
Thanks for the review @aceboogie8519! The Nmap project does not allow direct merges on GitHub, but does merge these pull requests manually to the svn repository, as described in the [CONTRIBUTING.md](https://github.com/nmap/nmap/blob/master/CONTRIBUTING.md#pull-requests). If you find this PR useful, you could discuss it on the [Nmap Development Mailing List](https://seclists.org/nmap-dev/) as a reply to [Re: Where to report incorrect mac prefixes](https://seclists.org/nmap-dev/2022/q2/7).

2022-06-13 15:25 UTC, aceboogie8519 commented
Yeah and I will tell them you hacked my shit and stole all my info. I'm new to these u fuck

2022-06-13 17:21 UTC, aceboogie8519 requested changes
Its has a vires. You have to get it debuged

2022-06-13 17:22 UTC, aceboogie8519 commented
The dude from these page is a crazy old man.

2022-06-20 16:56 UTC, fyodor commented
Thanks @oh2fih! I'm adding this to our roadmap for the next Nmap release. Also I just blocked @aceboogie8519.

2022-09-08 23:40 UTC, dmiller-nmap commented
Thanks for this contribution. The MA-L (OUI) registration data is still available in the same text format: https://regauth.standards.ieee.org/standards-ra-web/pub/view.html#registries

I just finished pushing a change to allow parsing and processing of MA-M and MA-S registrations as well. Unfortunately, this means that your script is not compatible, though users may find it helpful if they need updated registration data sooner than we get around to regenerating nmap-mac-prefixes.

2022-09-08 23:40 UTC, closed without merging

2022-09-09 05:45 UTC, oh2fih commented
It's the results that matter, whether this script was used or not. 

I find the header of `nmap-mac-prefixes` a bit confusing with the old URLs in it. Also, as the list is now sorted, the additions aren't at the end anymore. Would it be possible to update the header to match the contents?

> ```
> # $Id: $ generated with make-mac-prefixes.pl
> # Original data comes from http://standards.ieee.org/regauth/oui/oui.txt
> # These values are known as Organizationally Unique Identifiers (OUIs)
> # See http://standards.ieee.org/faqs/OUI.html
> # We have added a few unregistered OUIs at the end.
> ```

The main benefit of this `make-mac-prefixes.py` was that the manual additions were made automatically by the script, which would help others to update the list by themselves between the release cycles. In my opinion, the `make-mac-prefixes.pl` could be available & have this feature, too.

2022-09-09 15:16 UTC, dmiller-nmap commented
We can definitely update that text and better document the additions. FYI, here was the commit that changed the matching and parsing code in Nmap: 7013eefb050ca06c44a39b1a5c01d9283508a461